### ISSUE TITLE
`pip install` fails

### ISSUE THREAD

**Issue by glyph** [atomgomba/txtable#1]
```console
$ pip install txtable
Collecting txtable
  Downloading http://127.0.0.1:3141/root/pypi/+f/216/b90072c042fd8/txtable-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5z/sbg483yj7031bkxcptzpyh5w0000gn/T/pip-build-gofvmext/txtable/setup.py", line 8, in <module>
        long_description=open("README.rst").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5z/sbg483yj7031bkxcptzpyh5w0000gn/T/pip-build-gofvmext/txtable/
```

**Comment by atomgomba** [comment]
removing pip cache (eg. `rm -rf ~/.cache/pip`) should now fix it
